### ISSUE TITLE
Create timer and button 

### ISSUE THREAD

**Issue by mvchn** [trngl8/timer-button#1]
The timer and the button must be shown in the default state after load.
On the click button event, the timer must be started, and the seconds must be running; the button must be set into a running state.
On the click button event during running, the timer must be stopped and the button must be returned to the default state.

Bootstrap CSS framework can be used.

**Comment by ACraft4** [comment]
In progress

**Comment by mvchn** [comment]
https://github.com/trngl8/timer-button/commit/015d9f9a09416666266b7e7e69704aad777441bb
